/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'passenger' : IDL.Null,
  'admin' : IDL.Null,
  'advertiser' : IDL.Null,
  'driver' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'cpf' : IDL.Opt(IDL.Text),
  'carModel' : IDL.Opt(IDL.Text),
  'adsLink' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'subscriptionExpiry' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'subscriptionPlan' : IDL.Text,
  'state' : IDL.Text,
  'deviceId' : IDL.Text,
  'maxMinutesPerTrip' : IDL.Opt(IDL.Nat),
  'isBanned' : IDL.Bool,
  'paymentLink' : IDL.Opt(IDL.Text),
  'totalEarnings' : IDL.Opt(IDL.Nat),
  'minuteRate' : IDL.Opt(IDL.Nat),
  'carPlate' : IDL.Opt(IDL.Text),
  'freeMinutes' : IDL.Opt(IDL.Nat),
  'avatar' : IDL.Opt(ExternalBlob),
  'qrCode' : IDL.Opt(IDL.Text),
});
export const AdminStats = IDL.Record({
  'totalBanned' : IDL.Nat,
  'totalPassengers' : IDL.Nat,
  'totalDrivers' : IDL.Nat,
  'totalAdvertisers' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdRequest = IDL.Record({
  'id' : IDL.Text,
  'contactLink' : IDL.Text,
  'video' : ExternalBlob,
  'city' : IDL.Text,
  'createdAt' : Time,
  'advertiser' : IDL.Principal,
});
export const Ad = IDL.Record({
  'id' : IDL.Text,
  'contactLink' : IDL.Text,
  'video' : ExternalBlob,
  'city' : IDL.Text,
  'createdAt' : Time,
  'viewCount' : IDL.Nat,
  'approved' : IDL.Bool,
  'advertiser' : IDL.Principal,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'pix' : IDL.Null,
  'cash' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'passenger' : IDL.Principal,
  'paymentMethod' : PaymentMethod,
  'minutes' : IDL.Nat,
  'amount' : IDL.Nat,
  'driver' : IDL.Principal,
});
export const TripStatus = IDL.Variant({
  'requested' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : TripStatus,
  'passenger' : IDL.Principal,
  'paidMinutes' : IDL.Nat,
  'totalPaid' : IDL.Nat,
  'freeMinutesUsed' : IDL.Nat,
  'driver' : IDL.Principal,
});
export const PendingTimeRequest = IDL.Record({
  'passenger' : IDL.Principal,
  'driver' : IDL.Principal,
  'requestedMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminBanUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'adminGetAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminSaveUserDeviceId' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAdvertiserMonthlyViews' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdvertisersByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllAdRequests' : IDL.Func([], [IDL.Vec(AdRequest)], ['query']),
  'getAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAllAdvertisers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllDriverProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getApprovedAdsForCity' : IDL.Func([IDL.Text], [IDL.Vec(Ad)], ['query']),
  'getAvailableDriversByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAvailablePassengersByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConfirmedDriversByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getDriverMonthlyEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getDriverProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Text], [Payment], ['query']),
  'getPendingTimeRequestsForDriverProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PendingTimeRequest)],
      ['query'],
    ),
  'getRideHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
  'getSessionsForDriverProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Trip)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedDriversByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'passenger' : IDL.Null,
    'admin' : IDL.Null,
    'advertiser' : IDL.Null,
    'driver' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'cpf' : IDL.Opt(IDL.Text),
    'carModel' : IDL.Opt(IDL.Text),
    'adsLink' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'subscriptionExpiry' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'subscriptionPlan' : IDL.Text,
    'state' : IDL.Text,
    'deviceId' : IDL.Text,
    'maxMinutesPerTrip' : IDL.Opt(IDL.Nat),
    'isBanned' : IDL.Bool,
    'paymentLink' : IDL.Opt(IDL.Text),
    'totalEarnings' : IDL.Opt(IDL.Nat),
    'minuteRate' : IDL.Opt(IDL.Nat),
    'carPlate' : IDL.Opt(IDL.Text),
    'freeMinutes' : IDL.Opt(IDL.Nat),
    'avatar' : IDL.Opt(ExternalBlob),
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const AdminStats = IDL.Record({
    'totalBanned' : IDL.Nat,
    'totalPassengers' : IDL.Nat,
    'totalDrivers' : IDL.Nat,
    'totalAdvertisers' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdRequest = IDL.Record({
    'id' : IDL.Text,
    'contactLink' : IDL.Text,
    'video' : ExternalBlob,
    'city' : IDL.Text,
    'createdAt' : Time,
    'advertiser' : IDL.Principal,
  });
  const Ad = IDL.Record({
    'id' : IDL.Text,
    'contactLink' : IDL.Text,
    'video' : ExternalBlob,
    'city' : IDL.Text,
    'createdAt' : Time,
    'viewCount' : IDL.Nat,
    'approved' : IDL.Bool,
    'advertiser' : IDL.Principal,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'pix' : IDL.Null, 'cash' : IDL.Null });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'passenger' : IDL.Principal,
    'paymentMethod' : PaymentMethod,
    'minutes' : IDL.Nat,
    'amount' : IDL.Nat,
    'driver' : IDL.Principal,
  });
  const TripStatus = IDL.Variant({
    'requested' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : TripStatus,
    'passenger' : IDL.Principal,
    'paidMinutes' : IDL.Nat,
    'totalPaid' : IDL.Nat,
    'freeMinutesUsed' : IDL.Nat,
    'driver' : IDL.Principal,
  });
  const PendingTimeRequest = IDL.Record({
    'passenger' : IDL.Principal,
    'driver' : IDL.Principal,
    'requestedMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminBanUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'adminGetAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminSaveUserDeviceId' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAdvertiserMonthlyViews' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdvertisersByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllAdRequests' : IDL.Func([], [IDL.Vec(AdRequest)], ['query']),
    'getAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAllAdvertisers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllDriverProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getApprovedAdsForCity' : IDL.Func([IDL.Text], [IDL.Vec(Ad)], ['query']),
    'getAvailableDriversByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAvailablePassengersByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConfirmedDriversByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getDriverMonthlyEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getDriverProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Text], [Payment], ['query']),
    'getPendingTimeRequestsForDriverProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PendingTimeRequest)],
        ['query'],
      ),
    'getRideHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
    'getSessionsForDriverProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Trip)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedDriversByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };