/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : string,
  'contactLink' : string,
  'video' : ExternalBlob,
  'city' : string,
  'createdAt' : Time,
  'viewCount' : bigint,
  'approved' : boolean,
  'advertiser' : Principal,
}
export interface AdRequest {
  'id' : string,
  'contactLink' : string,
  'video' : ExternalBlob,
  'city' : string,
  'createdAt' : Time,
  'advertiser' : Principal,
}
export interface AdminStats {
  'totalBanned' : bigint,
  'totalPassengers' : bigint,
  'totalDrivers' : bigint,
  'totalAdvertisers' : bigint,
  'activeSubscriptions' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Payment {
  'id' : string,
  'status' : PaymentStatus,
  'passenger' : Principal,
  'paymentMethod' : PaymentMethod,
  'minutes' : bigint,
  'amount' : bigint,
  'driver' : Principal,
}
export type PaymentMethod = { 'pix' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface PendingTimeRequest {
  'passenger' : Principal,
  'driver' : Principal,
  'requestedMinutes' : bigint,
}
export type Time = bigint;
export interface Trip {
  'id' : string,
  'startTime' : Time,
  'status' : TripStatus,
  'passenger' : Principal,
  'paidMinutes' : bigint,
  'totalPaid' : bigint,
  'freeMinutesUsed' : bigint,
  'driver' : Principal,
}
export type TripStatus = { 'requested' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'id' : Principal,
  'cpf' : [] | [string],
  'carModel' : [] | [string],
  'adsLink' : [] | [string],
  'city' : string,
  'subscriptionExpiry' : bigint,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'subscriptionPlan' : string,
  'state' : string,
  'deviceId' : string,
  'maxMinutesPerTrip' : [] | [bigint],
  'isBanned' : boolean,
  'paymentLink' : [] | [string],
  'totalEarnings' : [] | [bigint],
  'minuteRate' : [] | [bigint],
  'carPlate' : [] | [string],
  'freeMinutes' : [] | [bigint],
  'avatar' : [] | [ExternalBlob],
  'qrCode' : [] | [string],
}
export type UserRole = { 'passenger' : null } |
  { 'admin' : null } |
  { 'advertiser' : null } |
  { 'driver' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminBanUser' : ActorMethod<[Principal], boolean>,
  'adminDeleteUser' : ActorMethod<[Principal], boolean>,
  'adminGetAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'adminSaveUserDeviceId' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getAdvertiserMonthlyViews' : ActorMethod<[], bigint>,
  'getAdvertisersByCity' : ActorMethod<[string], Array<UserProfile>>,
  'getAllAdRequests' : ActorMethod<[], Array<AdRequest>>,
  'getAllAds' : ActorMethod<[], Array<Ad>>,
  'getAllAdvertisers' : ActorMethod<[], Array<UserProfile>>,
  'getAllDriverProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllSessions' : ActorMethod<[], Array<Trip>>,
  'getApprovedAdsForCity' : ActorMethod<[string], Array<Ad>>,
  'getAvailableDriversByCity' : ActorMethod<[string], Array<UserProfile>>,
  'getAvailablePassengersByCity' : ActorMethod<[string], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConfirmedDriversByCity' : ActorMethod<[string], Array<UserProfile>>,
  'getDriverMonthlyEarnings' : ActorMethod<[], bigint>,
  'getDriverProfile' : ActorMethod<[Principal], UserProfile>,
  'getPaymentStatus' : ActorMethod<[string], Payment>,
  'getPendingTimeRequestsForDriverProfile' : ActorMethod<
    [Principal],
    Array<PendingTimeRequest>
  >,
  'getRideHistory' : ActorMethod<[Principal], Array<Trip>>,
  'getSessionsForDriverProfile' : ActorMethod<[Principal], Array<Trip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedDriversByCity' : ActorMethod<[string], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];