/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trip {
    id: string;
    startTime: Time;
    status: TripStatus;
    passenger: Principal;
    paidMinutes: bigint;
    totalPaid: bigint;
    freeMinutesUsed: bigint;
    driver: Principal;
}
export type Time = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: string;
    status: PaymentStatus;
    passenger: Principal;
    paymentMethod: PaymentMethod;
    minutes: bigint;
    amount: bigint;
    driver: Principal;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AdminStats {
    totalBanned: bigint;
    totalPassengers: bigint;
    totalDrivers: bigint;
    totalAdvertisers: bigint;
    activeSubscriptions: bigint;
}
export interface PendingTimeRequest {
    passenger: Principal;
    driver: Principal;
    requestedMinutes: bigint;
}
export interface AdRequest {
    id: string;
    contactLink: string;
    video: ExternalBlob;
    city: string;
    createdAt: Time;
    advertiser: Principal;
}
export interface UserProfile {
    id: Principal;
    cpf?: string;
    carModel?: string;
    adsLink?: string;
    city: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: Time;
    role: UserRole;
    subscriptionPlan: string;
    state: string;
    deviceId: string;
    maxMinutesPerTrip?: bigint;
    isBanned: boolean;
    paymentLink?: string;
    totalEarnings?: bigint;
    minuteRate?: bigint;
    carPlate?: string;
    freeMinutes?: bigint;
    avatar?: ExternalBlob;
    qrCode?: string;
}
export interface Ad {
    id: string;
    contactLink: string;
    video: ExternalBlob;
    city: string;
    createdAt: Time;
    viewCount: bigint;
    approved: boolean;
    advertiser: Principal;
}
export enum PaymentMethod {
    pix = "pix",
    cash = "cash"
}
export enum PaymentStatus {
    pending = "pending",
    confirmed = "confirmed"
}
export enum TripStatus {
    requested = "requested",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    passenger = "passenger",
    admin = "admin",
    advertiser = "advertiser",
    driver = "driver"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminBanUser(userId: Principal): Promise<boolean>;
    adminDeleteUser(userId: Principal): Promise<boolean>;
    adminGetAllProfiles(): Promise<Array<UserProfile>>;
    adminGetStats(): Promise<AdminStats>;
    adminSaveUserDeviceId(deviceId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    getAdvertiserMonthlyViews(): Promise<bigint>;
    getAdvertisersByCity(city: string): Promise<Array<UserProfile>>;
    getAllAdRequests(): Promise<Array<AdRequest>>;
    getAllAds(): Promise<Array<Ad>>;
    getAllAdvertisers(): Promise<Array<UserProfile>>;
    getAllDriverProfiles(): Promise<Array<UserProfile>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProfiles(): Promise<Array<UserProfile>>;
    getAllSessions(): Promise<Array<Trip>>;
    getApprovedAdsForCity(city: string): Promise<Array<Ad>>;
    getAvailableDriversByCity(city: string): Promise<Array<UserProfile>>;
    getAvailablePassengersByCity(city: string): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getConfirmedDriversByCity(city: string): Promise<Array<UserProfile>>;
    getDriverMonthlyEarnings(): Promise<bigint>;
    getDriverProfile(driver: Principal): Promise<UserProfile>;
    getPaymentStatus(sessionId: string): Promise<Payment>;
    getPendingTimeRequestsForDriverProfile(driver: Principal): Promise<Array<PendingTimeRequest>>;
    getRideHistory(passenger: Principal): Promise<Array<Trip>>;
    getSessionsForDriverProfile(driver: Principal): Promise<Array<Trip>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedDriversByCity(city: string): Promise<Array<UserProfile>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Ad as _Ad, AdRequest as _AdRequest, ExternalBlob as _ExternalBlob, Payment as _Payment, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Time as _Time, Trip as _Trip, TripStatus as _TripStatus, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminBanUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanUser(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminGetAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllProfiles();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllProfiles();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async adminSaveUserDeviceId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSaveUserDeviceId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSaveUserDeviceId(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAdvertiserMonthlyViews(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvertiserMonthlyViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvertiserMonthlyViews();
            return result;
        }
    }
    async getAdvertisersByCity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvertisersByCity(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvertisersByCity(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdRequests(): Promise<Array<AdRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdRequests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdRequests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAds(): Promise<Array<Ad>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAds();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAds();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdvertisers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdvertisers();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdvertisers();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDriverProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDriverProfiles();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDriverProfiles();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSessions(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedAdsForCity(arg0: string): Promise<Array<Ad>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedAdsForCity(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedAdsForCity(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableDriversByCity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDriversByCity(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDriversByCity(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailablePassengersByCity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailablePassengersByCity(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailablePassengersByCity(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfirmedDriversByCity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfirmedDriversByCity(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfirmedDriversByCity(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverMonthlyEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverMonthlyEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverMonthlyEarnings();
            return result;
        }
    }
    async getDriverProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverProfile(arg0);
                return from_candid_UserProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverProfile(arg0);
            return from_candid_UserProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentStatus(arg0: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentStatus(arg0);
                return from_candid_Payment_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentStatus(arg0);
            return from_candid_Payment_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTimeRequestsForDriverProfile(arg0: Principal): Promise<Array<PendingTimeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTimeRequestsForDriverProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTimeRequestsForDriverProfile(arg0);
            return result;
        }
    }
    async getRideHistory(arg0: Principal): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRideHistory(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRideHistory(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionsForDriverProfile(arg0: Principal): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsForDriverProfile(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsForDriverProfile(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedDriversByCity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedDriversByCity(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedDriversByCity(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AdRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdRequest): Promise<AdRequest> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Ad_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ad): Promise<Ad> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    cpf: [] | [string];
    carModel: [] | [string];
    adsLink: [] | [string];
    city: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    subscriptionPlan: string;
    state: string;
    deviceId: string;
    maxMinutesPerTrip: [] | [bigint];
    isBanned: boolean;
    paymentLink: [] | [string];
    totalEarnings: [] | [bigint];
    minuteRate: [] | [bigint];
    carPlate: [] | [string];
    freeMinutes: [] | [bigint];
    avatar: [] | [_ExternalBlob];
    qrCode: [] | [string];
}): Promise<{
    id: Principal;
    cpf?: string;
    carModel?: string;
    adsLink?: string;
    city: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: Time;
    role: UserRole;
    subscriptionPlan: string;
    state: string;
    deviceId: string;
    maxMinutesPerTrip?: bigint;
    isBanned: boolean;
    paymentLink?: string;
    totalEarnings?: bigint;
    minuteRate?: bigint;
    carPlate?: string;
    freeMinutes?: bigint;
    avatar?: ExternalBlob;
    qrCode?: string;
}> {
    return {
        id: value.id,
        cpf: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.cpf)),
        carModel: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.carModel)),
        adsLink: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.adsLink)),
        city: value.city,
        subscriptionExpiry: value.subscriptionExpiry,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        subscriptionPlan: value.subscriptionPlan,
        state: value.state,
        deviceId: value.deviceId,
        maxMinutesPerTrip: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxMinutesPerTrip)),
        isBanned: value.isBanned,
        paymentLink: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paymentLink)),
        totalEarnings: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.totalEarnings)),
        minuteRate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.minuteRate)),
        carPlate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.carPlate)),
        freeMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.freeMinutes)),
        avatar: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.avatar)),
        qrCode: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.qrCode))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactLink: string;
    video: _ExternalBlob;
    city: string;
    createdAt: _Time;
    advertiser: Principal;
}): Promise<{
    id: string;
    contactLink: string;
    video: ExternalBlob;
    city: string;
    createdAt: Time;
    advertiser: Principal;
}> {
    return {
        id: value.id,
        contactLink: value.contactLink,
        video: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.video),
        city: value.city,
        createdAt: value.createdAt,
        advertiser: value.advertiser
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactLink: string;
    video: _ExternalBlob;
    city: string;
    createdAt: _Time;
    viewCount: bigint;
    approved: boolean;
    advertiser: Principal;
}): Promise<{
    id: string;
    contactLink: string;
    video: ExternalBlob;
    city: string;
    createdAt: Time;
    viewCount: bigint;
    approved: boolean;
    advertiser: Principal;
}> {
    return {
        id: value.id,
        contactLink: value.contactLink,
        video: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.video),
        city: value.city,
        createdAt: value.createdAt,
        viewCount: value.viewCount,
        approved: value.approved,
        advertiser: value.advertiser
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    passenger: Principal;
    paymentMethod: _PaymentMethod;
    minutes: bigint;
    amount: bigint;
    driver: Principal;
}): {
    id: string;
    status: PaymentStatus;
    passenger: Principal;
    paymentMethod: PaymentMethod;
    minutes: bigint;
    amount: bigint;
    driver: Principal;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n27(_uploadFile, _downloadFile, value.status),
        passenger: value.passenger,
        paymentMethod: from_candid_PaymentMethod_n29(_uploadFile, _downloadFile, value.paymentMethod),
        minutes: value.minutes,
        amount: value.amount,
        driver: value.driver
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    status: _TripStatus;
    passenger: Principal;
    paidMinutes: bigint;
    totalPaid: bigint;
    freeMinutesUsed: bigint;
    driver: Principal;
}): {
    id: string;
    startTime: Time;
    status: TripStatus;
    passenger: Principal;
    paidMinutes: bigint;
    totalPaid: bigint;
    freeMinutesUsed: bigint;
    driver: Principal;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_TripStatus_n34(_uploadFile, _downloadFile, value.status),
        passenger: value.passenger,
        paidMinutes: value.paidMinutes,
        totalPaid: value.totalPaid,
        freeMinutesUsed: value.freeMinutesUsed,
        driver: value.driver
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passenger: null;
} | {
    admin: null;
} | {
    advertiser: null;
} | {
    driver: null;
}): UserRole {
    return "passenger" in value ? UserRole.passenger : "admin" in value ? UserRole.admin : "advertiser" in value ? UserRole.advertiser : "driver" in value ? UserRole.driver : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pix: null;
} | {
    cash: null;
}): PaymentMethod {
    return "pix" in value ? PaymentMethod.pix : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TripStatus {
    return "requested" in value ? TripStatus.requested : "completed" in value ? TripStatus.completed : "inProgress" in value ? TripStatus.inProgress : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdRequest>): Promise<Array<AdRequest>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AdRequest_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ad>): Promise<Array<Ad>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Ad_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    cpf?: string;
    carModel?: string;
    adsLink?: string;
    city: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: Time;
    role: UserRole;
    subscriptionPlan: string;
    state: string;
    deviceId: string;
    maxMinutesPerTrip?: bigint;
    isBanned: boolean;
    paymentLink?: string;
    totalEarnings?: bigint;
    minuteRate?: bigint;
    carPlate?: string;
    freeMinutes?: bigint;
    avatar?: ExternalBlob;
    qrCode?: string;
}): Promise<{
    id: Principal;
    cpf: [] | [string];
    carModel: [] | [string];
    adsLink: [] | [string];
    city: string;
    subscriptionExpiry: bigint;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    subscriptionPlan: string;
    state: string;
    deviceId: string;
    maxMinutesPerTrip: [] | [bigint];
    isBanned: boolean;
    paymentLink: [] | [string];
    totalEarnings: [] | [bigint];
    minuteRate: [] | [bigint];
    carPlate: [] | [string];
    freeMinutes: [] | [bigint];
    avatar: [] | [_ExternalBlob];
    qrCode: [] | [string];
}> {
    return {
        id: value.id,
        cpf: value.cpf ? candid_some(value.cpf) : candid_none(),
        carModel: value.carModel ? candid_some(value.carModel) : candid_none(),
        adsLink: value.adsLink ? candid_some(value.adsLink) : candid_none(),
        city: value.city,
        subscriptionExpiry: value.subscriptionExpiry,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n41(_uploadFile, _downloadFile, value.role),
        subscriptionPlan: value.subscriptionPlan,
        state: value.state,
        deviceId: value.deviceId,
        maxMinutesPerTrip: value.maxMinutesPerTrip ? candid_some(value.maxMinutesPerTrip) : candid_none(),
        isBanned: value.isBanned,
        paymentLink: value.paymentLink ? candid_some(value.paymentLink) : candid_none(),
        totalEarnings: value.totalEarnings ? candid_some(value.totalEarnings) : candid_none(),
        minuteRate: value.minuteRate ? candid_some(value.minuteRate) : candid_none(),
        carPlate: value.carPlate ? candid_some(value.carPlate) : candid_none(),
        freeMinutes: value.freeMinutes ? candid_some(value.freeMinutes) : candid_none(),
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n43(_uploadFile, _downloadFile, value.avatar)) : candid_none(),
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    passenger: null;
} | {
    admin: null;
} | {
    advertiser: null;
} | {
    driver: null;
} {
    return value == UserRole.passenger ? {
        passenger: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.advertiser ? {
        advertiser: null
    } : value == UserRole.driver ? {
        driver: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
